import Compiler;

compileFile("FMMLx/Auxiliaries",true,true);
compileFile("FMMLx/Boot",true,true);
compileFile("FMMLx/Manifest",true,true);
compileFile("FMMLx/Level",true,true);
compileFile("FMMLx/MetaAdaptor",true,true);
compileFile("FMMLx/FmmlxObject",true,true);
compileFile("FMMLx/FmmlxPackage",true,true);
compileFile("FMMLx/MetaClass",true,true);
compileFile("FMMLx/Issue",true,true);
