import Compiler;

compileFile("Clients/FmmlxDiagrams/Boot",true,true);
compileFile("Clients/FmmlxDiagrams/Manifest",true,true);
compileFile("Clients/FmmlxDiagrams/FmmlxDiagrams",true,true);
compileFile("Clients/FmmlxDiagrams/MappingInfo",true,true);
compileFile("Clients/FmmlxDiagrams/FmmlxDiagramMapping",true,true);
compileFile("Clients/FmmlxDiagrams/FmmlxDiagramClient",true,true);
compileFile("Clients/FmmlxDiagrams/FmmlxDiagram",true,true);
