import Compiler;

compileFile("Clients/FmmlxDiagrams/Boot",true,true);
compileFile("Clients/FmmlxDiagrams/Manifest",true,true);
compileFile("Clients/FmmlxDiagrams/FmmlxDiagrams",true,true);
compileFile("Clients/FmmlxDiagrams/FmmlxDiagramClient",true,true);
